Repository reactiveui/ReactiveUI, pull requests merged in 2018-05, with the labels that each got.

#1606 housekeeping: fix configuration for tizen
  GitReleaseManager.yaml
Labels: housekeeping

#1620 fix: disable WeakEventManager for net461 build (#1617)
  src/ReactiveUI/ReactiveList.cs
  src/ReactiveUI/ReactiveObject.cs
  src/ReactiveUI/WeakEventManager.cs
Labels: windows-presentation-foundation

#1626 [WIP] housekeeping: resolve broken build due to NET45 compilation symbol
  src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.approved.txt
  src/ReactiveUI/ReactiveList.cs
Labels: housekeeping

#1638 housekeeping: added codeowners convention
  .github/CODEOWNERS
Labels: housekeeping

#1607 Added basic Bind support to macOS for NSControls
  src/ReactiveUI/Platforms/apple-common/ObservableForPropertyBase.cs
  src/ReactiveUI/Platforms/ios/UIKitObservableForProperty.cs
  src/ReactiveUI/Platforms/mac/AppKitObservableForProperty.cs
  src/ReactiveUI/Platforms/mac/PlatformRegistrations.cs
Labels: xamarin-ios, xamarin-mac

#1527 housekeeping: add ReactiveUI.LeakTest project
  build.cake
  src/ReactiveUI.LeakTests/ReactiveUI.LeakTests.csproj
  src/ReactiveUI.sln
Labels: consumer-experience, contributor-experience, help wanted, housekeeping, maintainer-experience

#1653 housekeeping: updated stalebot message
  .github/stale.yml
Labels: housekeeping
