Repository reactiveui/ReactiveUI, pull requests merged in 2018-08, with the labels that each got.

#1631 Xamarin forms 3.0
  src/EventBuilder/Platforms/XamForms.cs
  src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
  src/ReactiveUI.XamForms/ReactiveUI.XamForms.csproj
Labels: xamarin-forms

#1703 housekeeping: Splat 4.0.2 is now required to fix MsBuild.Sdk.Extras issues
  src/ReactiveUI.AndroidSupport/ReactiveUI.AndroidSupport.csproj
  src/ReactiveUI.Blend/ReactiveUI.Blend.csproj
  src/ReactiveUI/ReactiveUI.csproj
Labels: bug

#1701 feat: Update ReactiveUI to use Reactive Extensions 4.0.0 as minimum
  src/Directory.build.targets
  src/ReactiveUI.AndroidSupport/ReactiveUI.AndroidSupport.csproj
  src/ReactiveUI.Blend/ReactiveUI.Blend.csproj
  src/ReactiveUI.Events.WPF/ReactiveUI.Events.WPF.csproj
  src/ReactiveUI.Events.Winforms/ReactiveUI.Events.Winforms.csproj
  src/ReactiveUI.Events.XamForms/ReactiveUI.Events.XamForms.csproj
  src/ReactiveUI.Events/ReactiveUI.Events.csproj
  src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
  src/ReactiveUI.Fody.Tests/ReactiveUI.Fody.Tests.csproj
  src/ReactiveUI.Testing/ReactiveUI.Testing.csproj
  src/ReactiveUI.Tests/ReactiveUI.Tests.csproj
  src/ReactiveUI/Platforms/netcoreapp2.1/PlatformRegistrations.cs
  src/ReactiveUI/ReactiveUI.csproj
Labels: reactiveui-core

#1707 bug: Fix the project to use TargetFrameworks
  src/ReactiveUI.Wpf/ReactiveUI.Wpf.csproj
Labels: bug, windows-presentation-foundation

#1705 housekeeping: Update the testing projects and cake file to have latest nuget packages.
  build.cake
  script/setversion.csproj
  src/ReactiveUI.Fody.Tests/ReactiveUI.Fody.Tests.csproj
  src/ReactiveUI.LeakTests/ReactiveUI.LeakTests.csproj
  src/ReactiveUI.Tests/ReactiveUI.Tests.csproj
Labels: housekeeping

#1708 housekeeping: Fix typos and broken links in readme
  README.md
Labels: documentation

#1709 Bug Make SourceLink the latest version.
  src/Directory.build.props
Labels: bug, build

#1710 Fix WPF users not having themes set correctly.
  src/Directory.build.props
  src/ReactiveUI.Wpf/ReactiveUI.Wpf.csproj
  src/ReactiveUI.sln
  src/global.json
Labels: bug, windows-presentation-foundation

#1702 Fix: Made POCOObservableForProperty include property name in warning
  src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.approved.txt
  src/ReactiveUI.Tests/API/ApiApprovalTests.Winforms.approved.txt
  src/ReactiveUI.Tests/INPCObservableForPropertyTests.cs
  src/ReactiveUI.Tests/Platforms/winforms/DefaultPropertyBindingTests.cs
  src/ReactiveUI.Tests/Platforms/xaml/DependencyObjectObservableForPropertyTest.cs
  src/ReactiveUI.Tests/PocoObservableForPropertyTests.cs
  src/ReactiveUI.Winforms/WinformsCreatesObservableForProperty.cs
  src/ReactiveUI.Wpf/WpfDependencyObjectObservableForProperty.cs
  src/ReactiveUI/INPCObservableForProperty.cs
  src/ReactiveUI/IROObservableForProperty.cs
  src/ReactiveUI/POCOObservableForProperty.cs
  src/ReactiveUI/Platforms/android/AndroidObservableForWidgets.cs
  src/ReactiveUI/Platforms/apple-common/KVOObservableForProperty.cs
  src/ReactiveUI/Platforms/apple-common/ObservableForPropertyBase.cs
  src/ReactiveUI/Platforms/uap10.0.16299/DependencyObjectObservableForProperty.cs
  src/ReactiveUI/ReactiveNotifyPropertyChangedMixin.cs
  src/ReactiveUI/ReactiveUI.csproj
  src/ReactiveUI/RegisterableInterfaces.cs
Labels: bug

#1616 Fix: change exceptions to have meaningful directions to documentation to help users.
  src/ReactiveUI/Platforms/netstandard2.0/PlatformRegistrations.cs
  src/ReactiveUI/Platforms/windows-common/RoutedViewHost.cs
  src/ReactiveUI/Platforms/windows-common/ViewModelViewHost.cs
  src/ReactiveUI/ReactiveNotifyPropertyChangedMixin.cs
Labels: consumer-experience, documentation

#1717 Allow building against prerelease versions of VS
  build.cake
Labels: housekeeping

#1718 housekeeping: Add Glen Watson to Core Team (#1718)
  README.md
Labels: housekeeping

#1655 [XamForms] Allow navigation transition animations to be disabled
  src/ReactiveUI.XamForms/DisableAnimationAttribute.cs
  src/ReactiveUI.XamForms/RoutedViewHost.cs
Labels: blocked, xamarin-forms

#1730 feature: Add a constructor to take the constructor to RoutingState
  src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.approved.txt
  src/ReactiveUI/RoutingState.cs
Labels: performance
