Repository reactiveui/ReactiveUI, pull requests merged in 2019-08, with the labels that each got.

#2130 Bump System.Reactive, fix ReactiveUI.Uno compilation
  src/Directory.build.props
  src/ReactiveUI.Fody.Helpers/ReactiveUI.Fody.Helpers.csproj
  src/ReactiveUI.Testing/ReactiveUI.Testing.csproj
  src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.net461.approved.txt
  src/ReactiveUI.Tests/API/ApiApprovalTests.ReactiveUI.netcoreapp2.0.approved.txt
  src/ReactiveUI.Tests/API/ApiApprovalTests.Testing.net461.approved.txt
  src/ReactiveUI.Tests/API/ApiApprovalTests.Testing.netcoreapp2.0.approved.txt
  src/ReactiveUI.Tests/Platforms/wpf/API/ApiApprovalTests.Wpf.net461.approved.txt
  src/ReactiveUI.Uno/ActivationForViewFetcher.cs
  src/ReactiveUI/Interfaces/IHasScheduler.cs
  src/ReactiveUI/ReactiveUI.csproj
Labels: dependencies, housekeeping

#2136 docs: add uno platform to readme
  README.md
Labels: documentation, platform-uno

#2134 docs: add the uno platform, remove windows store
  src/Directory.build.props
Labels: consumer-experience, documentation, housekeeping
