Repository reactiveui/ReactiveUI, pull requests merged in 2020-10, with the labels that each got.

#2549 Mention ReactiveUI.Blazor in README.md
  README.md
Labels: documentation

#2558 Update unsupported expression error messages
  src/ReactiveUI.Tests/WhenAny/ReactiveNotifyPropertyChangedMixinTest.cs
  src/ReactiveUI/Expression/ExpressionRewriter.cs
  src/ReactiveUI/Mixins/ExpressionMixins.cs
Labels: Hacktoberfest-accepted

#2561 housekeeping: Mention ReactiveUI.AndroidX
  README.md
Labels: documentation

#2560 Unit Tests for Xamarin.Forms RoutedViewHost (#2332)
  build.cake
  src/ReactiveUI.XamForms.Tests/Mocks/ChildView.cs
  src/ReactiveUI.XamForms.Tests/Mocks/ChildViewModel.cs
  src/ReactiveUI.XamForms.Tests/Mocks/MainView.cs
  src/ReactiveUI.XamForms.Tests/Mocks/MainViewModel.cs
  src/ReactiveUI.XamForms.Tests/Mocks/NavigationViewModel.cs
  src/ReactiveUI.XamForms.Tests/ReactiveUI.XamForms.Tests.csproj
  src/ReactiveUI.XamForms.Tests/RoutedViewHostTest.cs
  src/ReactiveUI.sln
Labels: Hacktoberfest-accepted

#2545 feature: Adding WhenActivated functionality to Android ViewHolders
  src/ReactiveUI.AndroidSupport/ReactiveRecyclerViewViewHolder.cs
  src/ReactiveUI.AndroidX/ReactiveRecyclerViewViewHolder.cs
Labels: Hacktoberfest-accepted

#2563 housekeeping: Release 12.1
  version.json
Labels: RELEASE

#2569 fix: TransitionContentControl throwing exception on control height zero
  src/ReactiveUI.Wpf/TransitioningContentControl.cs
Labels: release
